### ISSUE TITLE
Welcome page code example immediately gives errors, UI glitches

### ISSUE THREAD

**Issue by jbone** [codedownio/codedown-issues#3] opened 2017-04-27 21:06 UTC
Running the Python "hello world" cell in the Welcome document (whether by clicking the button or shift-enter) on Mac Sierra (10.12.4) yields the following error upon first attempt:

Interpreter error: src/IHaskell/IPython/Message/Parser.hs:33:29-68: Non-exhaustive patterns in record update

Subsequent attempts to evaluate the cell give:

Interpreter error: ZMQError { errno = 156384763, source = "send", message = "Operation cannot be accomplished in current state" }

Aside, detail and UI glitchiness:

After the first attempt, there is a "Python busy" indication in the top-right area, along with a black square;  attempts to put the cursor on any part of that set of controls causes them to disappear from the tool bar and another set consisting of the recycle, black square and a red X control to appear immediately below the blue tool bar in the top right --- but trying to move over *those* causes them to disappear and the original controls to appear in the tool bar.

**Comment by codedownio** [comment] 2017-08-14 19:54
Sorry, I somehow missed the Github notification from this. The UI and general stability has improved a lot since you filed and I can't reproduce this problem. Any chance you could try it again to confirm it's fixed?

**Comment by codedownio** [comment] 2017-08-20 04:53
Closing since believed fixed.

**Closed as completed by codedownio** 2017-08-20 04:53 UTC
